[package]
name = "hbuild"
version = "0.1.0"
edition = "2021"

[dependencies]
lexopt = "0.3.0"
owo-colors = "4.0.0"
indicatif = "0.17.8"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
toml = "0.8"
serde_json = "1.0"
hcl = { package = "hcl-rs", version = "0.19.4" }

